### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by oguerrer** [GGiecold/Cluster_Ensembles#5]
Hello,

Thanks for your contribution, I am trying to run it in python 2.7, anaconda distribution, following your example and I get the following error when running the cluster_ensembles command:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 297, in cluster_ensembles
    store_hypergraph_adjacency(hypergraph_adjacency, hdf5_file_name)
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 190, in store_hypergraph_adjacency
    FILTERS = get_compression_filter(byte_counts)
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 138, in get_compression_filter
    if 2 \* byte_counts > 1000 \* memory()['free']:
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 63, in memory
    with open('/proc/meminfo') as file:
IOError: [Errno 2] No such file or directory: '/proc/meminfo'

Do you have any idea what could be the problem?

Thanks

**Comment by GGiecold-zz** [comment]
/proc/meminfo is the path to a file in Linux, holding information about
free memory.

Cluster_Ensembles was never meant to be compatible with Windows or OS X.

A fix would involve using the psutil module to change the getChunkSize from
the Cluster_Ensembles package:

> > > import psutil
> > > mem = psutil.virtual_memory()
> > > free = mem['free']

Gregory

**Comment by oguerrer** [comment]
Thanks a lot. This got me one step closer. Now I am getting the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/Users/me/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/Users/me/Dropbox/Projects/dynamicLogrolling/code/04 - qualityFunction.py", line 100, in <module>
    consensus_clustering_labels = CE.cluster_ensembles(MC)
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 301, in cluster_ensembles
    cluster_ensemble.append(consensus_functions[i](hdf5_file_name, cluster_runs, verbose, N_clusters_max))
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 615, in CSPA
    return metis(hdf5_file_name, N_clusters_max)
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 938, in metis
    labels = sgraph(N_clusters_max, file_name)
  File "/Users/me/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 1202, in sgraph
    with open(out_name, 'r') as file:
IOError: [Errno 2] No such file or directory: 'wgraph_CSPA.part.370'

Any ideas?

**Comment by GGiecold-zz** [comment]
Check that gpmetis is up and running on your machine.

Gregory

**Comment by Jack-Lin-DS-AI** [comment]
Thanks Gregory. 
@oguerrer, here are what I did to make it work in Mac system:
1. Change 'memory' function in Cluster_Ensembles.py in Cluster_Ensembles packages (e.g., ~/anaconda/lib/python2.7/site-packages/Cluster_Ensembles/Cluster_Ensembles.py)
`import psutil`
`mem = psutil.virtual_memory()`
`mem_info['free'] = mem.free`
`mem_info['used'] = mem.used`
2. Download METIS binary file 'gpmetis' from https://github.com/mjdousti/Squash/tree/master/metis/mac
4. Add the path (e.g., ~/bin) to gpmetis in .bash_profile
`export PATH="~/bin:$PATH"`

**Comment by GGiecold-zz** [comment]
Exactly right.

Note that this issue doesn't arise for shmetis, which Cluster_Ensembles
compiles on your machine.

Gregory

**Comment by isvanilin** [comment]
Thank you guys for the conversation - it helped me to run the library under OSX. 
Unfortunately I am having the same issue with the last error: FileNotFoundError: [Errno 2] No such file or directory: 'wgraph_CSPA.part.50'. 
I have experimented with different ways to add path to file gpmetis and finally Ive put it into usr/local/bin and now Im getting same error saying "Permission denied" both in terminal and in PyCharm. 

Would appreciate any help!

**Comment by Jack-Lin-DS-AI** [comment]
You might need to change the permission of the file gpmetis.
Go to the directory, e.g., `cd usr/local/bin`
`chmod 755 gpmetis`

**Comment by isvanilin** [comment]
Thank you, ChihHsuLin! It worked.

**Comment by isvanilin** [comment]
There is another problem arising:
 File "/usr/local/lib/python3.5/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 309, in cluster_ensembles
    cluster_ensemble.append(consensus_functions[i](hdf5_file_name, cluster_runs, verbose, N_clusters_max))
  File "/usr/local/lib/python3.5/site-packages/Cluster_Ensembles/Cluster_Ensembles.py", line 727, in MCLA
    temp = squared_MCLA[i:min(i+chunks_size, N_rows), :].todense()
  File "/usr/local/lib/python3.5/site-packages/scipy/sparse/csr.py", line 285, in __getitem__
    return self._get_submatrix(row, col)
  File "/usr/local/lib/python3.5/site-packages/scipy/sparse/csr.py", line 428, in _get_submatrix
    check_bounds(i0, i1, M)
  File "/usr/local/lib/python3.5/site-packages/scipy/sparse/csr.py", line 424, in check_bounds
    " %d <= %d" % (i0, num, i1, num, i0, i1))
IndexError: index out of bounds: 0 <= 184973695 <= 2387, 0 <= 2387 <= 2387, 184973695 <= 2387

I have not installed metis library (there is a DLL issue), just used the bin file gpmetis.
Probably Gregory meant it when he wrote that  Cluster_Ensembles has never meant to run under OSX

**Comment by stshi8808** [comment]
Hello,.Thank you for helping.I am trying to run it in python 2.7 on windows,how can I make it work.I have no idea to get a solution. I'm a newer. 

I'm looking forward to your help.Thanks a lot.

**Comment by GGiecold-zz** [comment]
As mentioned in Cluster_Ensemble's PyPI and GitHub documentations, only
POSIX-compatible operating systems are supported.

Please try on Linux or OS X and let me know of any issue you might
encounter then.

Gregory

**Comment by stshi8808** [comment]
Thanks a lot for helping me. When I use the package,I want to get each labels results of the samples with CSPA,HGPA,MCLA. I try to do like this as an example: 
```
import numpy as np
import Cluster_Ensembles as CE
cluster_runs = np.random.randint(0, 8, (11, 50))
CSPA_clustering_labels = CE.CSPA(**hdf5_file_name**,cluster_runs, verbose = True, N_clusters_max = 8)
print CSPA_clustering_labels
```
But I don't know how to set the first Parameter(hdf5_file_name),because I don't have a hdf5_file.Could you give me the answer of above example?I am really newer in python.
Thanks a lot.I'm looking forward to your help.Thanks a lot.

**Comment by GGiecold-zz** [comment]
Please refer to the documentation of PyTables for installation of this
package, its dependencies (including the HDF5 C library and numexpr), as
well as basic I/O operations with *.h5 files.

Gregory

**Comment by stshi8808** [comment]
Thanks Gregory，I tried the following code with referring to the Cluster_ensembles function to build the .h5 file, like this:
```
import numpy as np
import Cluster_Ensembles as CE
import tables
cluster_runs = np.random.randint(0, 8, (15, 150))
hdf5_file_name = './Cluster_Ensembles.h5'
fileh = tables.open_file(hdf5_file_name, 'w')
fileh.create_group(fileh.root, 'consensus_group')
fileh.close()
hypergraph_adjacency = CE.build_hypergraph_adjacency(cluster_runs)
CE.store_hypergraph_adjacency(hypergraph_adjacency, hdf5_file_name)
consensus_clustering_labels = CE.CSPA(hdf5_file_name,cluster_runs, verbose = True, N_clusters_max = 8)
```
But the error is 
`AttributeError: 'module' object has no attribute 'build_hypergraph_adjacency'`
so the build_hypergraph_adjacency can not be imported?How can I correct it？
Thanks a lot.

**Comment by stshi8808** [comment]
These days I tried to use Cluster_Ensembles package to do my paper. I want to get each labels results of the samples with CSPA,HGPA,MCLA. I try to do like this as an example: 
```
import numpy as np
import Cluster_Ensembles as CE
import tables
cluster_runs = np.random.randint(0, 8, (15, 150))
hdf5_file_name = './Cluster_Ensembles.h5'
fileh = tables.open_file(hdf5_file_name, 'w')
fileh.create_group(fileh.root, 'consensus_group')
fileh.close()
hypergraph_adjacency = CE.build_hypergraph_adjacency(cluster_runs)
CE.store_hypergraph_adjacency(hypergraph_adjacency, hdf5_file_name)
consensus_clustering_labels = CE.HGPA(hdf5_file_name,cluster_runs, verbose = True, N_clusters_max = 8)
```
But there is an error:IOError: [Errno 2] No such file or directory: 'wgraph_HGPA.part.4'
But the MCLA and CSPA are available to get the result,only HGPA can't work.Can you help me?

**Comment by GGiecold-zz** [comment]
Possibly with some more detail?

**Comment by stshi8808** [comment]
Can you try the following code:
```
import numpy as np
import Cluster_Ensembles as CE
import tables
cluster_runs = np.random.randint(0, 8, (15, 150))
hdf5_file_name = './Cluster_Ensembles.h5'
fileh = tables.open_file(hdf5_file_name, 'w')
fileh.create_group(fileh.root, 'consensus_group')
fileh.close()
hypergraph_adjacency = CE.build_hypergraph_adjacency(cluster_runs)
CE.store_hypergraph_adjacency(hypergraph_adjacency, hdf5_file_name)
consensus_clustering_labels = CE.HGPA(hdf5_file_name,cluster_runs, verbose = True, N_clusters_max = 8)
print consensus_clustering_labels
```
The output : IOError: [Errno 2] No such file or directory: 'wgraph_HGPA.part.4' ,I don't know how to solve this problerm

**Comment by stshi8808** [comment]
Thanks Gregory,I try the these coede:
```
import numpy as np
import Cluster_Ensembles as CE
import tables
cluster_runs = np.random.randint(0, 8, (15, 150))
hdf5_file_name = './Cluster_Ensembles.h5'
fileh = tables.open_file(hdf5_file_name, 'w')
fileh.create_group(fileh.root, 'consensus_group')
fileh.close()
hypergraph_adjacency = CE.build_hypergraph_adjacency(cluster_runs)
CE.store_hypergraph_adjacency(hypergraph_adjacency, hdf5_file_name)
consensus_clustering_labels = CE.CSPA(hdf5_file_name,cluster_runs, verbose = True, N_clusters_max = 8)
print consensus_clustering_labels
```
It can work successfully. Also MCLA is also successful. Only HGPA has that error:No such file or directory: 'wgraph_HGPA.part.4' .
Hope your reply, sorry to dsiturb.

**Comment by stshi8808** [comment]
The output is 
```
*****
INFO: Cluster_Ensembles: HGPA: consensus clustering using HGPA.

#
INFO: Cluster_Ensembles: wgraph: writing wgraph_HGPA.
INFO: Cluster_Ensembles: wgraph: 15 vertices and 23 non-zero hyper-edges.
#

#
INFO: Cluster_Ensembles: sgraph: calling shmetis for hypergraph partitioning.
/bin/sh: 1: /home/shituo/Hypergraph_Partitioning/hmetis-1.5-linux/shmetis: not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shituo/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 922, in runfile
    execfile(filename, namespace)
  File "/home/shituo/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 95, in execfile
    builtins.execfile(filename, *where)
  File "/home/shituo/crazy.py", line 1295, in <module>
    consensus_clustering_labels = HGPA(hdf5_file_name,cluster_runs, verbose = True, N_clusters_max = 4)
  File "/home/shituo/crazy.py", line 622, in HGPA
    return hmetis(hdf5_file_name, N_clusters_max)
  File "/home/shituo/crazy.py", line 947, in hmetis
    labels = sgraph(N_clusters_max, file_name)
  File "/home/shituo/crazy.py", line 1175, in sgraph
    with open(out_name, 'r') as file:
IOError: [Errno 2] No such file or directory: 'wgraph_HGPA.part.4'
```

**Comment by stshi8808** [comment]
Where can I get shmetis?

**Comment by stshi8808** [comment]
I find the shmetis, It can work now.Thanks a lot

**Comment by GGiecold-zz** [comment]
That was a common problem. Metis and shmetis are supposed to be compiled
when installing Cluster_Ensemble. On some machines (including yours), they
do not. Marco Sardelich posted a little fix some time ago on
Cluster_Ensemble page on GitHub.

Glad it works now and all the best with your research.

Gregory

**Comment by FatimaAnwer** [comment]
@GGiecold @ChihHsuLin @oguerrer @isvanilin @stshi8808 Please help me with the second error. I have tried so many ways to add path but I am still getting the error:
IOError: [Errno 2] No such file or directory: 'wgraph_CSPA.part.50'

I am working on a Mac. I downloaded gpmetis.dms but I have no clue what to do with it. Should I run it or should I put it in the right directory. Please help.

**Comment by Lirunhua** [comment]
@FatimaAnwer you have to mv the 'gpmetis' file to dir:  /usr/local/bin
and 👍 
chmod 755 gpmetis

**Comment by nafisegh** [comment]
@GGiecold @ChihHsuLin @oguerrer @isvanilin @stshi8808 
Please help me.
I want to use Cluster_Ensembles library for my research. I am using google colab, but when I use this command  "consensus_clustering_labels=CE.cluster_ensembles(final_ensemble,N_clusters_max=int(np.max(final_ensemble)+1))"

 I got this error:

*****
INFO: Cluster_Ensembles: CSPA: consensus clustering using CSPA.

#
INFO: Cluster_Ensembles: wgraph: writing wgraph_CSPA.
#

#
INFO: Cluster_Ensembles: sgraph: calling gpmetis for graph partitioning.


IOErrorTraceback (most recent call last)

<ipython-input-12-3408e9771f9a> in <module>()
      3 #from functools import reduce
      4 
----> 5 consensus_clustering_labels=CE.cluster_ensembles(final_ensemble,N_clusters_max=int(np.max(final_ensemble)+1))

3 frames

/usr/local/lib/python2.7/dist-packages/Cluster_Ensembles/Cluster_Ensembles.pyc in sgraph(N_clusters_max, file_name)
   1199 
   1200     labels = np.empty(0, dtype = int)
-> 1201     with open(out_name, 'r') as file:
   1202         print("INFO: Cluster_Ensembles: sgraph: (hyper)-graph partitioning completed; "
   1203               "loading {}".format(out_name))

IOError: [Errno 2] No such file or directory: 'wgraph_CSPA.part.15'


I read the last comments, but I am still confused about which file "gpmetis or shmetis" I must download and how can I add this file to a path in google colab?
