### ISSUE TITLE
Parellel processing

### ISSUE THREAD

**Issue by Jack-Lin-DS-AI** [GGiecold/Cluster_Ensembles#6]
Does current version allow python to call more than twice Cluster_Ensembles on the same machine? Thank you.

**Comment by Jack-Lin-DS-AI** [comment]
I tried to create and enter a temporary folder for each time I execute Cluster_Ensembles, but it didn't work.

**Comment by GGiecold-zz** [comment]
I do not see any obstacle to processing in parallel (with the
multiprocessing or the concurrent.futures modules from the Python
standard library) multiple, distinct ensembles of partitions, provided
each Cluster_Ensemble job is called with its own dedicated *.h5 file.

As for a multiprocessing implementation of a single consensus clustering
task, that would involve the kind of complications that have been
addressed in Concurrent_AP (lock conditions on an HDF5 file, etc.).

Gregory

**Comment by GGiecold-zz** [comment]
Willing to share any detail?

**Comment by Jack-Lin-DS-AI** [comment]
I found I did something wrong in my code. And it works now. Thank you.
